name: Release - Build & Push Python App Docker Image

on:
  push:
    tags:
      - "v*.*.*"   # ex: v1.0.0
    paths:
      - "ChessAnywhereServer/**"
  pull_request:
    tags:
      - "v*.*.*"   # ex: v1.0.0
    paths:
      - "ChessAnywhereServer/**"

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ChessAnywhereServer
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/ChessAnywhereServer
          VERSION=${GITHUB_REF##*/}   # récupère le tag ex: v1.0.0
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/ChessAnywhereServer
          VERSION=${GITHUB_REF##*/}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION
