name: CI - Java Server

on:
  push:
    tags:
      - "v*.*.*"   # ex: v1.0.0
    paths:
      - "ChessAnywhereServer/**"
  pull_request:
    tags:
      - "v*.*.*"   # ex: v1.0.0
    paths:
      - "ChessAnywhereServer/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & test
        working-directory: server
        run: ./mvnw clean verify
