name: CI - Java Server

on:
  push:
    paths:
      - "ChessAnywhereServer/**"
  pull_request:
    paths:
      - "ChessAnywhereServer/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build & test
        working-directory: ChessAnywhereServer
        run: mvnw clean verify

      - name: Build Docker
        working-directory: ChessAnywhereServer
        run: mvnw clean package
          docker build …
          docker run …
          curl http://localhost:8080/health
