name: CI - Tests python

on:
  push:
    paths:
      - "app/**"
  pull_request:
    branches:
      - main     # run on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install pytest

      - name: Run tests
        run: PYTHONPATH=app pytest app/test
