name: CI - Tests python

on:
  push:
    paths:
      - "python-app/**"
  pull_request:
    paths:
      - "python-app/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: PYTHONPATH=. pytest --junitxml=pytest-report.xml python-app/test

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest-report.xml
