name: Build STM32 Firmware

on:
  push:
    paths:
      - "stm32-app/**"
  pull_request:
    paths:
      - "stm32-app/**"

jobs:
  build-flash:
    runs-on: self-hosted

    steps:
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u GianniCecchetto --password-stdin

      - name: Pull container
        run: docker pull ghcr.io/giannicecchetto/chessanywhere/stm32-runner:latest

      - name: Use container
        run: docker run --rm ghcr.io/giannicecchetto/chessanywhere/stm32-runner:latest

      - uses: actions/checkout@v3

      # Step 1: Build firmware
      - name: Build Firmware
        run: make

      # Step 2: Flash the STM32 (if hardware attached)
      # NOTE: This works only if the runner can access the hardware via USB
      - name: Flash STM32
        if: runner.os == 'Linux'
        run: |
          openocd -f interface/stlink.cfg -f target/stm32l0.cfg \
                  -c "program firmware.elf verify reset exit"
